/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 16/05/2017 10:51:10
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     16000000
#define MX_HCLKFreq_Value                       16000000
#define MX_FCLKCortexFreq_Value                 16000000
#define MX_CortexFreq_Value                     16000000
#define MX_AHBFreq_Value                        16000000
#define MX_APB1Freq_Value                       16000000
#define MX_APB2Freq_Value                       16000000
#define MX_APB1TimFreq_Value                    16000000
#define MX_APB2TimFreq_Value                    16000000
#define MX_EthernetFreq_Value                   16000000
#define MX_CECFreq_Value                        32786
#define MX_LCDTFToutputFreq_Value               48000000
#define MX_I2C1Freq_Value                       16000000
#define MX_I2C2Freq_Value                       16000000
#define MX_I2C3Freq_Value                       16000000
#define MX_I2C4Freq_Value                       16000000
#define MX_I2SFreq_Value                        96000000
#define MX_SAI1Freq_Value                       96000000
#define MX_SAI2Freq_Value                       96000000
#define MX_SDMMCFreq_Value                      16000000
#define MX_RTCFreq_Value                        32000
#define MX_USART1Freq_Value                     16000000
#define MX_USART2Freq_Value                     16000000
#define MX_USART3Freq_Value                     16000000
#define MX_UART4Freq_Value                      16000000
#define MX_UART5Freq_Value                      16000000
#define MX_UART8Freq_Value                      16000000
#define MX_UART7Freq_Value                      16000000
#define MX_USART6Freq_Value                     16000000
#define MX_USBFreq_Value                        96000000
#define MX_WatchDogFreq_Value                   32000
#define MX_LPTIM1Freq_Value                     16000000
#define MX_SPDIFRXFreq_Value                    96000000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    16000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_PA1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA1_Pin                              PA1
#define MX_PA1_GPIOx                            GPIOA
#define MX_PA1_PinState                         GPIO_PIN_RESET
#define MX_PA1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA1_GPIO_Pin                         GPIO_PIN_1
#define MX_PA1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD1 */
#define MX_PD1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD1_Pin                              PD1
#define MX_PD1_GPIOx                            GPIOD
#define MX_PD1_PinState                         GPIO_PIN_RESET
#define MX_PD1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD1_GPIO_Pin                         GPIO_PIN_1
#define MX_PD1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE1 */
#define MX_PE1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE1_Pin                              PE1
#define MX_PE1_GPIOx                            GPIOE
#define MX_PE1_PinState                         GPIO_PIN_RESET
#define MX_PE1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE1_GPIO_Pin                         GPIO_PIN_1
#define MX_PE1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB1 */
#define MX_PB1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_PinState                         GPIO_PIN_RESET
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC1 */
#define MX_PC1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC1_Pin                              PC1
#define MX_PC1_GPIOx                            GPIOC
#define MX_PC1_PinState                         GPIO_PIN_RESET
#define MX_PC1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC1_GPIO_Pin                         GPIO_PIN_1
#define MX_PC1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

